server{
	listen 80;
	location /{
		proxy_pass http://loaclhost:80;
		proxy_set_header Host $ host;
		proxy_set_header X-Real-IP $remote-addr;
		proxy_set_header X-forwarded-For $proxy_add_x_forwarded_for;
	}
}
