worker_processes auto;
pid /tmp/nginx.pid;

events{}

http{
  server{
    listen 8081;
    
    root /mnt/e/devops/nginx/POC/Nginx/newPOC/http;
    index index.html;

    location /fruits{
      root /mnt/e/devops/nginx/POC/Nginx/newPOC/http;
    }
    location /free{
      root /mnt/e/devops/nginx/POC/Nginx/newPOC/http;
      try_files /free/free.html /free.html =404;
    }
  }
}